[package]
name = "plrs-xilinx"
version = "0.1.0"
edition = "2024"
authors = ["Erik BÃ¥nvik <erik.public@gmail.com>"]
license = "MIT"

[dependencies]
uio-rs = { git = "https://github.com/blueluna/uio-rs.git" }
# uio-rs = { path = "../../uio-rs/uio-rs" }
log = "0.4"
